baseURL = "https://www.karpinski.tech/"
defaultContentLanguage = "pl"
languageCode = "pl-PL"

title = "My New Hugo Site"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

enableEmoji = true

[params]
  dateFormat = "2 January 2006"


[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posty"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tagi"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/MacKarp"
    weight = 3
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/maciej-karpi%C5%84ski-a9613a199/"
    weight = 4
    pre = "<span data-feather='linkedin'></span>"
  
  [[menu.main]]
    identifier = "facebook"
    url = "https://www.facebook.com/maciej.karpinski.39"
    weight = 5
    pre = "<span data-feather='facebook'></span>"


  [[menu.main]]
    identifier = "spotify"
    url = "https://open.spotify.com/user/karpfly"
    weight = 6
    pre = "<img class='svg-inject' src='/icons/spotify.svg' />" 


  [[menu.main]]
    identifier = "lubimy czytać"
    url = "https://lubimyczytac.pl/profil/188030/Maciej"
    weight = 7
    pre = "<span data-feather='book'></span>"

