baseURL = "https://www.karpinski.tech/"
defaultContentLanguage = "pl"
languageCode = "pl-PL"

title = "Maciej Karpiński"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

enableEmoji = true

[params]
  dateFormat = "Monday 2 January 2006"
  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-xl"
  description = "Inżynier informatyk, znawca technologii, miłośnik fantastyki, marzyciel."
  showPostsOnHomePage = "recent"
  footer = "Maciej Karpiński"

  socialIcons = [
      {name = "github", url = "https://github.com/MacKarp"},
      {name = "linkedin", url = "https://www.linkedin.com/in/maciej-karpi%C5%84ski-a9613a199/"},
      {name = "facebook",url="https://www.facebook.com/maciej.karpinski.39"},
      {name = "spotify", url = "https://open.spotify.com/user/karpfly"},
      {name = "book", url = "https://lubimyczytac.pl/profil/188030/Maciej"}
    ]


[menu]
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    pre = "<span data-feather='file-text'></span>"
    name = "Posty"
    weight = 1

  [[menu.main]]
    identifier = "projekty"
    url = "/projects/"
    pre = "<span data-feather='terminal'></span>"
    name = "Projekty"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tagi"
    url = "/tags/"
    weight = 3
    pre = "<span data-feather='tag'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/MacKarp"
    weight = 4
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/maciej-karpi%C5%84ski-a9613a199/"
    weight = 5
    pre = "<span data-feather='linkedin'></span>"
  
  [[menu.main]]
    identifier = "facebook"
    url = "https://www.facebook.com/maciej.karpinski.39"
    weight = 6
    pre = "<span data-feather='facebook'></span>"


  [[menu.main]]
    identifier = "spotify"
    url = "https://open.spotify.com/user/karpfly"
    weight = 7
    pre = "<img class='svg-inject' src='/icons/spotify.svg' />" 


  [[menu.main]]
    identifier = "lubimy czytać"
    url = "https://lubimyczytac.pl/profil/188030/Maciej"
    weight = 8
    pre = "<span data-feather='book'></span>"